version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the chroma_db directory to persist data
      - ./chroma_db:/code/chroma_db
      # Optional: Mount the source code for live-reloading during development
      - ./app:/code/app
    environment:
      # Example of setting environment variables
      # Create a .env file to manage these locally
      - CHROMA_PATH=/code/chroma_db
      # - API_KEY=your_secret_api_key
      # - NO_AUTH=False
    # The command can be overridden for development to enable --reload
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
